---
# Per environment values which override defaults in hmpps-approved-premises-manage-a-resident-ui/values.yaml

generic-service:
  replicaCount: 2

  ingress:
    host: approved-premises-manage-a-resident-dev.hmpps.service.justice.gov.uk
    tlsSecretName: hmpps-approved-premises-manage-a-resident-dev-cert

  env:
    INGRESS_URL: "https://approved-premises-manage-a-resident-dev.hmpps.service.justice.gov.uk"
    HMPPS_AUTH_URL: "https://sign-in-dev.hmpps.service.justice.gov.uk/auth"
    TOKEN_VERIFICATION_API_URL: "https://token-verification-api-dev.prison.service.justice.gov.uk"
    MANAGE_A_RESIDENT_API_URL: 'https://approved-premises-manage-a-resident-api-dev.hmpps.service.justice.gov.uk'
    ENVIRONMENT_NAME: DEV
    AUDIT_ENABLED: "false"

generic-prometheus-alerts:
  alertSeverity: hmpps-approved-premises
