---
# Per environment values which override defaults in hmpps-approved-premises-manage-a-resident-ui/values.yaml

generic-service:
  ingress:
    host: approved-premises-manage-a-resident-ui.hmpps.service.justice.gov.uk

  env:
    INGRESS_URL: "https://approved-premises-manage-a-resident-ui.hmpps.service.justice.gov.uk"
    HMPPS_AUTH_URL: "https://sign-in.hmpps.service.justice.gov.uk/auth"
    TOKEN_VERIFICATION_API_URL: "https://token-verification-api.prison.service.justice.gov.uk"
    MANAGE_A_RESIDENT_API_URL: 'https://approved-premises-manage-a-resident-api.hmpps.service.justice.gov.uk'
    AUDIT_ENABLED: "false"

generic-prometheus-alerts:
  alertSeverity: hmpps-approved-premises
